<?php

namespace ContainerAiM497x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOslControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OslController' shared autowired service.
     *
     * @return \App\Controller\OslController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/OslController.php';

        $container->services['App\\Controller\\OslController'] = $instance = new \App\Controller\OslController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\OslController', $container));

        return $instance;
    }
}
