<?php

namespace ContainerTm5oTxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddStampsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AddStampsController' shared autowired service.
     *
     * @return \App\Controller\AddStampsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AddStampsController.php';

        $container->services['App\\Controller\\AddStampsController'] = $instance = new \App\Controller\AddStampsController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\AddStampsController', $container));

        return $instance;
    }
}
