<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBe8CSdq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBe8CSdq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBe8CSdq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBe8CSdq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBe8CSdq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Be8CSdq',
    'container.build_id' => 'f29921b4',
    'container.build_time' => 1699351057,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBe8CSdq');
