<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_about' => [[], ['_controller' => 'App\\Controller\\AboutController::index'], [], [['text', '/about']], [], [], []],
    'app_add_news' => [[], ['_controller' => 'App\\Controller\\AddNewsController::index'], [], [['text', '/add/news']], [], [], []],
    'app_add_stamps' => [[], ['_controller' => 'App\\Controller\\AddStampsController::index'], [], [['text', '/add/stamps']], [], [], []],
    'app_adherer' => [[], ['_controller' => 'App\\Controller\\AdhererController::index'], [], [['text', '/adherer']], [], [], []],
    'app_brochure' => [[], ['_controller' => 'App\\Controller\\BrochureController::index'], [], [['text', '/brochure']], [], [], []],
    'app_cotisation' => [[], ['_controller' => 'App\\Controller\\CotisationController::index'], [], [['text', '/cotisation']], [], [], []],
    'app_forum' => [[], ['_controller' => 'App\\Controller\\ForumController::index'], [], [['text', '/forum']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_news' => [[], ['_controller' => 'App\\Controller\\NewsController::index'], [], [['text', '/news']], [], [], []],
    'app_osl' => [[], ['_controller' => 'App\\Controller\\OslController::index'], [], [['text', '/osl']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_stamps' => [[], ['_controller' => 'App\\Controller\\StampsController::index'], [], [['text', '/stamps']], [], [], []],
    'app_stamp_detail' => [['id'], ['_controller' => 'App\\Controller\\DetailController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/stamps/detail']], [], [], []],
    'stamp_upload' => [[], ['_controller' => 'App\\Controller\\StampController::upload'], [], [['text', '/upload']], [], [], []],
];
